# Import all models so Alembic can detect them
from app.models.base import Base, TimestampMixin, SoftDeleteMixin
from app.models.auth import User, RefreshToken, PasswordResetToken, UserRole
from app.models.organization import Company, Department, Designation
from app.models.employee import (
    Employee,
    EmployeeSkill,
    Skill,
    EmploymentHistory,
    EmployeeDocument,
    EmploymentType,
    EmploymentStatus,
    DocumentType,
)
from app.models.recruitment import (
    JobPosting,
    Candidate,
    Application,
    AIEvaluation,
    VoiceScreening,
    InterviewQuestions,
    Offer,
    JobStatus,
    ApplicationStage,
    OfferStatus,
)
from app.models.attendance import (
    AttendanceLog,
    AttendanceRegularization,
    AttendanceStatus,
    RegularizationStatus,
)
from app.models.leave import (
    LeaveType,
    LeaveBalance,
    LeaveRequest,
    LeaveApproval,
    Holiday,
    LeaveStatus,
)
from app.models.payroll import (
    SalaryStructure,
    EmployeeSalary,
    PayrollRun,
    PayrollEntry,
    PayrollStatus,
)
from app.models.performance import (
    PerformanceCycle,
    Goal,
    PerformanceReview,
    PerformanceScore,
    CycleType,
    CycleStatus,
    GoalStatus,
    ReviewType,
)
from app.models.notification import Notification

__all__ = [
    "Base",
    "TimestampMixin",
    "SoftDeleteMixin",
    "User",
    "RefreshToken",
    "PasswordResetToken",
    "UserRole",
    "Company",
    "Department",
    "Designation",
    "Employee",
    "EmployeeSkill",
    "Skill",
    "EmploymentHistory",
    "EmployeeDocument",
    "EmploymentType",
    "EmploymentStatus",
    "DocumentType",
    "JobPosting",
    "Candidate",
    "Application",
    "AIEvaluation",
    "VoiceScreening",
    "InterviewQuestions",
    "Offer",
    "JobStatus",
    "ApplicationStage",
    "OfferStatus",
    "AttendanceLog",
    "AttendanceRegularization",
    "AttendanceStatus",
    "RegularizationStatus",
    "LeaveType",
    "LeaveBalance",
    "LeaveRequest",
    "LeaveApproval",
    "Holiday",
    "LeaveStatus",
    "SalaryStructure",
    "EmployeeSalary",
    "PayrollRun",
    "PayrollEntry",
    "PayrollStatus",
    "PerformanceCycle",
    "Goal",
    "PerformanceReview",
    "PerformanceScore",
    "CycleType",
    "CycleStatus",
    "GoalStatus",
    "ReviewType",
    "Notification",
]
