import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useSearchParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Button,
  IconButton,
  Avatar,
  Slider,
  CircularProgress,
  List,
  ListItem,
  ListItemText,
  alpha,
  Divider,
  Paper,
  Chip,
} from '@mui/material';
import {
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
  KeyboardBackspace as BackIcon,
  VolumeUp as VolumeIcon,
  HelpOutline as QuestionIcon,
  Autorenew as GenerateIcon,
} from '@mui/icons-material';
import { recruitmentApi } from '@/api/recruitment.api';
import PageHeader from '@/components/ui/PageHeader';
import AIScoreCard from '@/components/ai/AIScoreCard';
import { toast } from 'react-hot-toast';

// Dummy voice screening assessment details for demonstration fallback
const defaultVoiceAssessment = {
  duration: '4 mins 24 secs',
  interviewer: 'HRGenie AI Assistant',
  communicationScore: 88,
  confidence: 90,
  technicalAccuracy: 84,
  grammarFluency: 92,
  transcript: [
    { speaker: 'Interviewer', text: 'Hello, thank you for taking the time to speak with us today. To start, can you summarize your experience building REST APIs with FastAPI?' },
    { speaker: 'Candidate', text: 'Sure! I have been building REST APIs with Python for about 4 years now. Over the last 2 years, I transitioned heavily to FastAPI. I love its type safety using Pydantic, its automatic Swagger documentation generation, and its speed using asynchronous event loops. In my last role, I designed and scaled microservices that handled around 5,000 requests per minute with sub-50ms latency.' },
    { speaker: 'Interviewer', text: 'Excellent details. How did you handle database sessions and connection pooling inside those async endpoints?' },
    { speaker: 'Candidate', text: 'We used SQLAlchemy 2.0 with the asyncpg driver. We utilized FastAPI dependency injection to yield a scoped database session per request. For connection pooling, we tuned SQLAlchemy pool_size and max_overflow parameters to scale dynamically during spike hours.' },
    { speaker: 'Interviewer', text: 'Thank you. What is your experience with Docker and setting up CI/CD pipelines?' },
    { speaker: 'Candidate', text: 'All our microservices are containerized. I write custom Multi-stage Dockerfiles to minimize build size. For CI/CD, we use GitHub Actions to run tests, perform static analysis with Ruff and mypy, build docker images, and push them to AWS ECR.' },
  ],
};

export default function VoiceScreening() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [searchParams] = useSearchParams();
  const applicationId = searchParams.get('applicationId') || '';

  const [isPlaying, setIsPlaying] = useState(false);
  const [playProgress, setPlayProgress] = useState(30); // Mock percentage

  // 1. Fetch application details
  const { data: detailData, isLoading } = useQuery({
    queryKey: ['application-detail', applicationId],
    queryFn: () => recruitmentApi.getApplication(applicationId),
    enabled: !!applicationId,
  });

  // 2. Fetch actual voice screening records
  const { data: screenings, isLoading: isLoadingScreenings } = useQuery({
    queryKey: ['voice-screenings', applicationId],
    queryFn: () => recruitmentApi.getVoiceScreenings(applicationId),
    enabled: !!applicationId,
  });

  // 3. Fetch/Generate interview questions
  const { data: questions, isLoading: isLoadingQuestions } = useQuery({
    queryKey: ['interview-questions', applicationId],
    queryFn: () => recruitmentApi.getInterviewQuestions(applicationId),
    enabled: !!applicationId,
  });

  // Mutation to generate interview questions
  const generateQuestionsMutation = useMutation({
    mutationFn: () => recruitmentApi.generateInterviewQuestions(applicationId, ['FastAPI', 'System Architecture', 'CI/CD']),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['interview-questions', applicationId] });
      toast.success('Interview questions generated by Gemini!');
    },
    onError: (err: any) => {
      toast.error(err.response?.data?.detail || 'Failed to generate interview questions.');
    },
  });

  const uploadVoiceMutation = useMutation({
    mutationFn: (file: File) => recruitmentApi.uploadVoiceScreening(applicationId, file),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['voice-screenings', applicationId] });
      queryClient.invalidateQueries({ queryKey: ['application-detail', applicationId] });
      toast.success('Voice screening audio uploaded and evaluated successfully!');
    },
    onError: (err: any) => {
      toast.error(err.response?.data?.detail || 'Failed to process voice screening.');
    },
  });

  const handleAudioUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      uploadVoiceMutation.mutate(e.target.files[0]);
    }
  };

  if (isLoading || isLoadingScreenings) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 10 }}>
        <CircularProgress color="secondary" />
      </Box>
    );
  }

  if (!detailData) {
    return (
      <Box sx={{ p: 4, textAlign: 'center' }}>
        <Typography color="error">Application not found.</Typography>
        <Button startIcon={<BackIcon />} onClick={() => navigate(-1)} sx={{ mt: 2 }}>
          Go Back
        </Button>
      </Box>
    );
  }

  const handlePlayToggle = () => {
    setIsPlaying(!isPlaying);
  };

  const handleGenerateQuestions = () => {
    generateQuestionsMutation.mutate();
  };

  // Check if AI Evaluation overall score is present
  const aiEval = detailData.ai_evaluation;
  const latestScreening = screenings && screenings.length > 0 ? screenings[screenings.length - 1] : null;

  return (
    <Box>
      <PageHeader
        title="AI Voice Screening"
        subtitle={`Review audio recording and AI voice interview screening insights for ${detailData.candidate_name}.`}
        action={
          <Button
            variant="outlined"
            startIcon={<BackIcon />}
            onClick={() => navigate(-1)}
            sx={{
              borderColor: alpha('#334155', 0.8),
              color: '#94A3B8',
              '&:hover': {
                borderColor: '#8B5CF6',
                background: alpha('#8B5CF6', 0.05),
              },
            }}
          >
            Back to Pipeline
          </Button>
        }
      />

      <Grid container spacing={3}>
        {/* Playback & Transcript (Left) */}
        <Grid item xs={12} lg={8}>
          <Card
            sx={{
              background: 'linear-gradient(145deg, #1E293B, #0F172A)',
              borderRadius: '16px',
              border: '1px solid #334155',
              mb: 3,
            }}
          >
            <CardContent sx={{ p: 3 }}>
              <Box display="flex" justifyContent="space-between" alignItems="center" mb={2}>
                <Typography variant="subtitle1" fontWeight={700} sx={{ color: '#F8FAFC' }}>
                  Interview Audio Playback
                </Typography>
                <Button
                  variant="outlined"
                  component="label"
                  size="small"
                  disabled={uploadVoiceMutation.isPending}
                  sx={{
                    color: '#10B981',
                    borderColor: alpha('#10B981', 0.4),
                    textTransform: 'none',
                    '&:hover': {
                      borderColor: '#10B981',
                      background: alpha('#10B981', 0.05),
                    },
                  }}
                >
                  {uploadVoiceMutation.isPending ? 'Processing Audio...' : 'Upload Screen Recording'}
                  <input
                    type="file"
                    accept="audio/*"
                    hidden
                    onChange={handleAudioUpload}
                  />
                </Button>
              </Box>

              {/* Waveform Player / Real Audio Player */}
              {latestScreening ? (
                <Box
                  sx={{
                    p: 3,
                    background: '#0F172A',
                    borderRadius: '12px',
                    border: '1px solid #334155',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 3,
                    mb: 4,
                  }}
                >
                  <audio
                    src={latestScreening.audio_url}
                    controls
                    style={{ width: '100%' }}
                  />
                </Box>
              ) : (
                <Box
                  sx={{
                    p: 3,
                    background: '#0F172A',
                    borderRadius: '12px',
                    border: '1px solid #334155',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 3,
                    mb: 4,
                  }}
                >
                  <IconButton
                    onClick={handlePlayToggle}
                    sx={{
                      bgcolor: '#8B5CF6',
                      color: '#FFF',
                      p: 2,
                      '&:hover': { bgcolor: '#7C3AED' },
                    }}
                  >
                    {isPlaying ? <PauseIcon /> : <PlayIcon />}
                  </IconButton>

                  <Box sx={{ flex: 1 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                      <Typography variant="caption" color="text.secondary">
                        {isPlaying ? '0:54' : '0:00'}
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        {defaultVoiceAssessment.duration}
                      </Typography>
                    </Box>
                    <Box
                      sx={{
                        height: 48,
                        display: 'flex',
                        alignItems: 'center',
                        gap: '3px',
                        mb: 1,
                      }}
                    >
                      {Array.from({ length: 48 }).map((_, i) => {
                        const active = i < 48 * (playProgress / 100);
                        const height = Math.abs(Math.sin(i * 0.4)) * 36 + 6;
                        return (
                          <Box
                            key={i}
                            sx={{
                              flex: 1,
                              height: height,
                              bgcolor: active ? '#8B5CF6' : '#334155',
                              borderRadius: '2px',
                              transition: 'bgcolor 0.2s',
                            }}
                          />
                        );
                      })}
                    </Box>
                    <Slider
                      value={playProgress}
                      onChange={(_, val) => setPlayProgress(val as number)}
                      size="small"
                      sx={{
                        color: '#8B5CF6',
                        padding: '0px 0',
                        '& .MuiSlider-thumb': { width: 8, height: 8 },
                      }}
                    />
                  </Box>

                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: '#94A3B8' }}>
                    <VolumeIcon />
                    <Typography variant="caption">100%</Typography>
                  </Box>
                </Box>
              )}

              <Typography variant="subtitle1" fontWeight={700} sx={{ color: '#F8FAFC', mb: 2 }}>
                Interview Transcript
              </Typography>
              <Paper
                elevation={0}
                sx={{
                  background: alpha('#0F172A', 0.5),
                  border: '1px solid #1E293B',
                  borderRadius: '12px',
                  maxHeight: 400,
                  overflowY: 'auto',
                  p: 2,
                  '&::-webkit-scrollbar': { width: 4 },
                  '&::-webkit-scrollbar-thumb': { background: '#334155', borderRadius: 2 },
                }}
              >
                {latestScreening ? (
                  <Box>
                    <Typography variant="body2" sx={{ color: '#E2E8F0', lineHeight: 1.6, whiteSpace: 'pre-line' }}>
                      {latestScreening.transcript}
                    </Typography>
                  </Box>
                ) : (
                  defaultVoiceAssessment.transcript.map((seg, idx) => (
                    <Box key={idx} sx={{ mb: 3 }}>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5 }}>
                        <Typography
                          variant="caption"
                          fontWeight={700}
                          sx={{
                            color: seg.speaker === 'Interviewer' ? '#8B5CF6' : '#10B981',
                          }}
                        >
                          {seg.speaker}
                        </Typography>
                      </Box>
                      <Typography variant="body2" sx={{ color: '#E2E8F0', lineHeight: 1.6 }}>
                        {seg.text}
                      </Typography>
                    </Box>
                  ))
                )}
              </Paper>
            </CardContent>
          </Card>

          {/* AI Tailored Interview Questions Section */}
          <Card
            sx={{
              background: 'linear-gradient(145deg, #1E293B, #0F172A)',
              borderRadius: '16px',
              border: '1px solid #334155',
            }}
          >
            <CardContent sx={{ p: 3 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
                <Typography variant="subtitle1" fontWeight={700} sx={{ color: '#F8FAFC' }}>
                  Tailored Interview Questions (Gemini Engine)
                </Typography>
                <Button
                  variant="outlined"
                  size="small"
                  startIcon={<GenerateIcon />}
                  onClick={handleGenerateQuestions}
                  disabled={generateQuestionsMutation.isPending}
                  sx={{
                    color: '#A78BFA',
                    borderColor: alpha('#8B5CF6', 0.4),
                    textTransform: 'none',
                    '&:hover': {
                      borderColor: '#8B5CF6',
                      background: alpha('#8B5CF6', 0.05),
                    },
                  }}
                >
                  {generateQuestionsMutation.isPending ? 'Generating...' : 'Generate New'}
                </Button>
              </Box>

              {isLoadingQuestions ? (
                <Box sx={{ py: 4, display: 'flex', justifyContent: 'center' }}>
                  <CircularProgress size={24} color="secondary" />
                </Box>
              ) : !questions || questions.length === 0 ? (
                <Typography color="text.secondary" variant="body2">
                  No interview questions generated yet. Click 'Generate New' to prompt the Gemini agent.
                </Typography>
              ) : (
                <List sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  {questions.map((q: any, i: number) => (
                    <Paper
                      elevation={0}
                      key={i}
                      sx={{
                        p: 2,
                        background: '#0F172A',
                        border: '1px solid #1E293B',
                        borderRadius: '10px',
                      }}
                    >
                      <ListItem sx={{ p: 0, alignItems: 'flex-start' }}>
                        <QuestionIcon sx={{ color: '#8B5CF6', mr: 2, mt: 0.2 }} />
                        <ListItemText
                          primary={
                            <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mb: 1 }}>
                              <Typography variant="body2" fontWeight={600} sx={{ color: '#F8FAFC' }}>
                                {q.question}
                              </Typography>
                              <Chip
                                label={q.category.toUpperCase()}
                                size="small"
                                sx={{
                                  fontSize: '0.6rem',
                                  height: 18,
                                  bgcolor: alpha('#8B5CF6', 0.15),
                                  color: '#A78BFA',
                                }}
                              />
                            </Box>
                          }
                          secondary={
                            <Box sx={{ mt: 1 }}>
                              <Typography variant="caption" sx={{ color: '#10B981', fontWeight: 600, display: 'block', mb: 0.5 }}>
                                Key Points to Check:
                              </Typography>
                              {q.expected_answer_points?.map((pt: string, pi: number) => (
                                <Typography key={pi} variant="caption" sx={{ color: '#94A3B8', display: 'block' }}>
                                  • {pt}
                                </Typography>
                              ))}
                            </Box>
                          }
                        />
                      </ListItem>
                    </Paper>
                  ))}
                </List>
              )}
            </CardContent>
          </Card>
        </Grid>

        {/* AI Assessment Scorecard (Right) */}
        <Grid item xs={12} lg={4}>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
            <AIScoreCard
              title="Voice Screening Rating"
              overallScore={latestScreening ? latestScreening.overall_voice_score : (aiEval ? aiEval.overall_score : defaultVoiceAssessment.communicationScore)}
              subMetrics={[
                {
                  label: 'Grammar & Fluency',
                  score: latestScreening?.ai_evaluation?.content_evaluation?.clarity_score || defaultVoiceAssessment.grammarFluency
                },
                {
                  label: 'Confidence Level',
                  score: latestScreening?.ai_evaluation?.content_evaluation?.confidence_score || defaultVoiceAssessment.confidence
                },
                {
                  label: 'Technical Relevance',
                  score: latestScreening?.ai_evaluation?.content_evaluation?.technical_accuracy_score || defaultVoiceAssessment.technicalAccuracy
                },
              ]}
            />

            <Card
              sx={{
                background: 'linear-gradient(145deg, #1E293B, #0F172A)',
                borderRadius: '16px',
                border: '1px solid #334155',
              }}
            >
              <CardContent sx={{ p: 2.5 }}>
                <Typography variant="subtitle2" sx={{ color: '#F8FAFC', fontWeight: 700, mb: 1.5 }}>
                  Voice Evaluation Report
                </Typography>
                <Typography variant="body2" sx={{ color: '#94A3B8', lineHeight: 1.6, mb: 2 }}>
                  {latestScreening?.ai_evaluation?.ai_summary ||
                    'The candidate displays outstanding communication skills and high confidence levels. Their technical descriptions of building REST APIs using FastAPI were extremely accurate, displaying deep familiarity with Python, Pydantic data schemas, SQLAlchemy async session patterns, and Docker multi-stage containers.'}
                </Typography>
                <Divider sx={{ borderColor: '#334155', my: 1.5 }} />
                <Typography variant="subtitle2" sx={{ color: '#F8FAFC', fontWeight: 700, mb: 1 }}>
                  Voice Analysis Metrics
                </Typography>
                <Grid container spacing={2}>
                  <Grid item xs={6}>
                    <Typography variant="caption" color="text.secondary">
                      Speech Rate
                    </Typography>
                    <Typography variant="body2" fontWeight={600} sx={{ color: '#F8FAFC' }}>
                      {latestScreening?.ai_evaluation?.speech_metrics?.words_per_minute
                        ? `${latestScreening.ai_evaluation.speech_metrics.words_per_minute} WPM`
                        : '135 WPM (Optimal)'}
                    </Typography>
                  </Grid>
                  <Grid item xs={6}>
                    <Typography variant="caption" color="text.secondary">
                      Hesitations
                    </Typography>
                    <Typography variant="body2" fontWeight={600} sx={{ color: '#EF4444' }}>
                      {latestScreening?.ai_evaluation?.speech_metrics?.filler_word_count !== undefined
                        ? `${latestScreening.ai_evaluation.speech_metrics.filler_word_count} counts`
                        : '4 counts (Very Low)'}
                    </Typography>
                  </Grid>
                  <Grid item xs={6}>
                    <Typography variant="caption" color="text.secondary">
                      Sentiment
                    </Typography>
                    <Typography variant="body2" fontWeight={600} sx={{ color: '#22C55E' }}>
                      Positive (94%)
                    </Typography>
                  </Grid>
                  <Grid item xs={6}>
                    <Typography variant="caption" color="text.secondary">
                      Clarity Rating
                    </Typography>
                    <Typography variant="body2" fontWeight={600} sx={{ color: '#22C55E' }}>
                      Excellent
                    </Typography>
                  </Grid>
                </Grid>
              </CardContent>
            </Card>
          </Box>
        </Grid>
      </Grid>
    </Box>
  );
}
